### PR TITLE
Fix undefined Date on Vitals - NEWS page

### PR DESCRIPTION
**Pull request by ZuzooVn**
There is the undefined date on Vitals - NEWS page.

screen shot 2017-06-02 at 4 11 01 pm

This pull request fixed this issue.

Best Regards.
Nam Vu from ThinkLabs-VN

### CODE REVIEW

**Comment by tony-shannon** [comment]
many thanks @ZuzooVn 
@robtweed you happy to merge?
thanks
T

**Comment by ZuzooVn** [comment]
Thanks @tony-shannon 
I have the same Pull request for PulseTile https://github.com/PulseTile/PulseTile/pull/7
Please take a look at it.

Thanks,
Nam Vu from ThinksLabs-VN

**Comment by tony-shannon** [comment]
Yes, noted, thanks, T

**Comment by robtweed** [comment]
Date change has been made to latest build: 2.24.0

**Comment by tony-shannon** [comment]
thanks @robtweed 
Can you update demo box with this code, retest and update here with a screenshot of it working now please?
This issue can then be closed off
thanks, 
Tony

**Comment by ZuzooVn** [comment]
Thanks @robtweed @tony-shannon ,

In the future, I think you should merge the pull request instead of directly changing the source code by yourself.

Thanks,
Nam Vu from ThinksLabs-VN

**Comment by tony-shannon** [comment]
Sorry @ZuzooVn , our mistake
Apologies
We've got github flow plan in place to sort these going forward.
thanks again for your help!
Tony

**Pull request closed without merging**
