### PR TITLE
minor edit to the capitalisation and formatting of 3)

### PR DESCRIPTION
**Pull request by pacharanero**
to clarify that the emphasis is on 'use ONE installer' (ie don't use more than one)

#hacktoberfest

### CODE REVIEW

**Comment by tony-shannon** [comment]
thanks Marcus
Can you send a single PR with all those typo changes to this repo?
Thanks
T

**Comment by tony-shannon** [comment]
If you're doing them inline then understand its fine
T

**Comment by pacharanero** [comment]
I've just been doing them inline in the GH editor which is great for
ultra-minor edits like this.

For the more serious documentation authoring I'll use a proper editor and
fewer PRs

M

**Comment by tony-shannon** [comment]
fine thanks
T

**Pull request merged**
